version: 2.1

orbs:
  sonarcloud: sonarsource/sonarcloud@2.0.0
  ggshield: gitguardian/ggshield@volatile

jobs:
  test:
    working_directory: ~/project
    docker:
      - image: cimg/python:3.9.20
    steps:
      - checkout
      - run: sudo apt install make
      - run: 
          name: Run test
          command: make test-report
      - store_test_results:
          path: test-results.xml
      - sonarcloud/scan
      - persist_to_workspace:
          root: ~/project
          paths: .
workflows:
  test:
    jobs:
      - test:
          context: SonarCloud
  scan:
    jobs:
      - ggshield/scan:
          name: ggshield-scan
          context: GitGuardian
          base_revision: << pipeline.git.base_revision >>
          revision: <<pipeline.git.revision>>  
