version: 2.1

orbs:
  sonarcloud: sonarsource/sonarcloud@2.0.0
  ggshield: gitguardian/ggshield@volatile

jobs:
  test:
    working_directory: ~/project
    docker:
      - image: cimg/python:3.9.20
    steps:
      - checkout
      - run:
          name: Install make
          command: sudo apt install make
      # - run: 
      #     name: Run lint
      #     command: make lint
      - run: 
          name: Run test
          command: make test-report
      - store_test_results:
          path: test-results.xml
      - sonarcloud/scan
      - persist_to_workspace:
          root: ~/project
          paths: .
  deploy:
    docker:
      - image: cimg/base:2024.10
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build and push to Docker Hub
          command: |
            docker build -t $DOCKER_HUB_USER_ID/$IMAGE_NAME:latest .
            echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_USER_ID" --password-stdin
            docker push $DOCKER_HUB_USER_ID/$IMAGE_NAME:latest



workflows:
  scan:
    jobs:
      - ggshield/scan:
          name: ggshield-scan
          context: GitGuardian
          base_revision: << pipeline.git.base_revision >>
          revision: <<pipeline.git.revision>>
  test-deploy:
    jobs:
      - test:
          context: SonarCloud
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: main        



