version: 2.1

orbs:
  sonarcloud: sonarsource/sonarcloud@2.0.0
  ggshield: gitguardian/ggshield@volatile

jobs:
  test:
    working_directory: ~/project
    docker:
      - image: cimg/python:3.9.20
    steps:
      - checkout
      - run:
          name: Install make
          command: sudo apt install make
      - run: 
          name: Run make lint
          command: make lint
      - run: 
          name: Run make test
          command: make test-report
      - store_test_results:
          path: test-results.xml
      - sonarcloud/scan
      - persist_to_workspace:
          root: ~/project
          paths: .
  build_and_push:
    docker:
      - image: cimg/base:2024.10
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Login to Docker Hub
          command: |
            echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_USER_ID" --password-stdin
      - run:
          name: Build and push Docker Image to Docker Hub
          command: |
            docker build -t $DOCKER_HUB_USER_ID/$IMAGE_NAME:${CIRCLE_BUILD_NUM} .
            docker push $DOCKER_HUB_USER_ID/$IMAGE_NAME:${CIRCLE_BUILD_NUM}
      - run:
          name: Clone Manifest Repository
          command: |
            # Clone the separate manifest repository
            git clone https://${GITHUB_TOKEN}@github.com/avaldominos/practica-cicd-avm-manifest.git manifests-repo
      - run:
          name: Update Kubernetes Manifest with New Image Tag
          command: |
            # Update the image tag in the Kubernetes manifest file (/k8s/deployment.yaml)
            sed -i "s|image: avaldominos/python-app:.*|image: avaldominos/python-app:${CIRCLE_BUILD_NUM}|" manifests-repo/k8s/deployment.yaml
      - run:
          name: Commit and Push Updated Manifest
          command: |
            cd manifests-repo
            git config --global user.email "avaldominos@alsyro.es"
            git config --global user.name "avaldominos"
            git add k8s/deployment.yaml
            git commit -m "Update image tag to ${CIRCLE_BUILD_NUM}"

            # Push changes back to the manifest repository
            git push origin main


workflows:

  test_scan_build_push:
    jobs:
      - test:
          context: SonarCloud
      - ggshield/scan:
          name: ggshield-scan
          context: GitGuardian
          base_revision: << pipeline.git.base_revision >>
          revision: <<pipeline.git.revision>>
      - build_and_push:
          requires:
            - test
          filters:
            branches:
              only: main            